//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventDataService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        public string Name { get; set; }
        public int NumInParty { get; set; }
        public string Message { get; set; }
        public Nullable<bool> willCome { get; set; }
    }
}
