//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joshnewton.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public Attendee()
        {
            this.RSVPs = new HashSet<RSVP>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string UID { get; set; }
    
        public virtual ICollection<RSVP> RSVPs { get; set; }
    }
}
