//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joshnewton.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVP
    {
        public int Id { get; set; }
        public int AttendeeId { get; set; }
        public int NumInParty { get; set; }
        public string Message { get; set; }
        public bool willCome { get; set; }
        public System.DateTime dtCreate { get; set; }
    
        public virtual Attendee Attendee { get; set; }
    }
}
