#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.2 on Sun Mar 11 18:17:21 2012
#IMPORT----------------------------------------------------
import wx, os, time
import easygui as eg

# begin wxGlade: extracode


os.chdir(os.getenv("USERPROFILE"))
os.chdir('./Desktop')
projectList = open('./projectList.txt').readlines()
projectList.insert(0, 'SELECT ONE')
class globalVars:
	project = str()
	t0 = str()
	timerTicking = False
	projectTime = int()
# end wxGlade


#WX Class--------------------------------------------------
class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.timer = self.CreateStatusBar(2, 0)
        self.label_1 = wx.StaticText(self, -1, "Select Project: ")
        self.combo_box_1 = wx.ComboBox(self, -1, choices=projectList, style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.startButton = wx.Button(self, -1, "Start")
        self.stopButton = wx.Button(self, -1, "Stop")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.selectProject, self.combo_box_1)
        self.Bind(wx.EVT_BUTTON, self.startTimer, self.startButton)
        self.Bind(wx.EVT_BUTTON, self.stopTimer, self.stopButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Project Timer")
        self.SetSize((270, 339))
        self.timer.SetStatusWidths([-1, -1])
        # statusbar fields
        timer_fields = ["Start Time: "]
        for i in range(len(timer_fields)):
            self.timer.SetStatusText(timer_fields[i], i)
        self.label_1.SetFont(wx.Font(13, wx.DECORATIVE, wx.NORMAL, wx.BOLD, 0, "Lucida Bright"))
        self.combo_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.label_1, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_1.Add(self.combo_box_1, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.startButton, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_2.Add(self.stopButton, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def startTimer(self, event): # wxGlade: MyFrame.<event_handler>
    	globalVars.t0 = time.time()
    	globalVars.timerTicking = True
    	self.timer.SetStatusText('Start Time: ' + time.strftime('%H:%M:%S'))

    def stopTimer(self, event): # wxGlade: MyFrame.<event_handler>
    	globalVars.timerTicking = False
    	projectTime = int(time.time() - globalVars.t0)
        f = open('./timesheet.txt', 'a')
        f.write(globalVars.project + "worked for: " + str(projectTime) + " secs\n")
        f.close()
        self.timer.SetStatusText('Start Time:')

    def selectProject(self, event): # wxGlade: MyFrame.<event_handler>
    	if globalVars.timerTicking == True:
    		eg.msgbox('Project already started', 'Cannot start timer')
    	else:
        	globalVars.project = str(self.combo_box_1.GetValue())

# end of class MyFrame

#MAIN---------------------------------------------------------------
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
